spring:
  profiles:
    active: local
# swaggerdoc
springdoc:
  version: v1.0.0
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  packages-to-scan: com.price.search.howmuchisit
  api-docs:
    path: /api-docs

naver:
  api:
    url: https://openapi.naver.com/v1/search/shop.json
    id:
    secret:

---
spring:
  config:
    activate:
      on-profile: local
  # db
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:scripts/schema.sql
      data-locations: classpath:scripts/data.sql

---
spring:
  config:
    activate:
      on-profile: alpha
  # db
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
