spring:
  # db
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
# db
# swaggerdoc
springdoc:
  version: v1.0.0
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  packages-to-scan: com.price.search.howmuchisit
  api-docs:
    path: /api-docs