### search case 1 이름 => CJ 삼호어묵 <b>오색어묵탕</b> 365G x 2개 8820
GET http://localhost:8080/api/v1/search/prices?query=오색어묵탕

### search case 2 상표 이름 => CJ 삼호어묵 <b>오색어묵탕</b> 365G x 2개 8820
GET http://localhost:8080/api/v1/search/prices?query=삼호 오색어묵탕

### search case 3 상표 이름 용량 => CJ 삼호어묵 <b>오색어묵탕</b> 365G x 2개 8820
GET http://localhost:8080/api/v1/search/prices?query=삼호 오색어묵탕 395g

### search case 4 상표 이름 용량 묶음 => empty
GET http://localhost:8080/api/v1/search/prices?query=삼호 오색어묵탕 395g*2입

### search case 5 상표 이름 용량 묶음 특수문자 제거 => empty
GET http://localhost:8080/api/v1/search/prices?query=삼호 오색어묵탕 395g 2입

### search case 6 상표 이름 용량 단위 제거 => CJ 삼호어묵 <b>오색어묵탕</b> 365G x 2개 8820
GET http://localhost:8080/api/v1/search/prices?query=삼호 오색어묵탕 395

### search case 7 상표 이름 용량 묶음 단위 제거 => empty
GET http://localhost:8080/api/v1/search/prices?query=삼호 오색어묵탕 395 2

### search case 8 단순 오타 => empty
GET http://localhost:8080/api/v1/search/prices?query=우색어묵탕

### search case 9 의미있는 오타 => 잡내없이 깊고 깔끔한 육수의 돼지국밥 고기국밥 국밥 700g 7500
GET http://localhost:8080/api/v1/search/prices?query=육색어묵탕

### search case 10 띄어쓰기 제거 => CJ 삼호어묵 <b>오색어묵탕</b> 365G x 2개 8820
GET http://localhost:8080/api/v1/search/prices?query=삼호오색어묵탕395g

### search case 11 띄어쓰기 제거 => 씨제이 <b>삼호오색어묵탕</b> 365Gx2입 13320
GET http://localhost:8080/api/v1/search/prices?query=삼호오색어묵탕395g2입